GrabarzUndPartner/gp-vue-boilerplate

package.json
=> fix(branch-name-linter): added

package.json
=> chore(package): update postcss-normalize to version 7.0.1

package.json
=> chore(package): update postcss-nested to version 4.1.0

src/components/atoms/Picture.vue
added http sources, replaced object via array, images now responsive
=> added http sources

.eslintrc
- array-bracket-newline
- no-multiple-empty-lines
- block-spacing
=> feat(eslint): added rules:

package-lock.json, package.json
=> Greenkeeper/nuxt i18n 6.1.3

.gitignore, .gitlab-ci.yml, package.json
=> feat(gitlab): gitlab-ci integration

package.json
=> fix(package): removed repo entry

package-lock.json, package.json
=> Feature/upgrade @storybook/addon actions from 5.2.1 to 5.2.3

package-lock.json, package.json
=> Feature/upgrade @storybook/vue from 5.2.1 to 5.2.3

package-lock.json, package.json, src/components/atoms/SvgInline.vue
=> feat(svg): update SvgInline

nuxt.config.js, package-lock.json, package.json, src/components/atoms/Picture.vue, src/components/organisms/Stage.vue, src/components/organisms/article/HeadlineText.vue, src/components/page/Footer.vue, src/components/page/Header.vue, src/layouts/default.vue, src/pages/index.vue
=> fix(object-fit-images): fixed picturefill init and object-fit-image

.releaserc, .travis.yml
=> fix(releaserc): updated config

.releaserc, CHANGELOG_PROJECT.md
=> fix(semantic-release): changed config

src/extends/ModuleLocales.vue, src/modules/virtual/Locales.js
change module root path from '@/locales' to '@/virtual-locales'
=> fix(locales): fix module compile

src/layouts/default.vue, src/utils/fonts.js
update fonts in default layout
=> feat(font-loader): update font-loader

.travis.yml
=> fix(mochawesome-merge): fix mochawesome-merge travis command

config.code-workspace
=> feat(vscode-stylelint): change stylelint plugin, update workspace config

.stylelintrc, config.code-workspace
=> feat(vscode-stylelint): update configs

CHANGELOG_PROJECT.md, src/layouts/default.vue
added initial CHANGELOG_PROJECT.md
=> feat(optimize): change prevent-scroll styleclass with data attribute

src/modules/svg.js
=> fix(svg-module): removed svg from the webpack image rule test

.gitignore, .vscode/launch.json, env/static-server.js
added command arguments and env support for port and dist
update gitignore
=> feat(update): added launch.json with debug task

.travis.yml, src/components/atoms/Headline.vue
=> feat(update): fix deprecated key skip_cleanup

.storybook/prepare/index.js, .storybook/prepare/style.css, .storybook/preview.js, src/components/atoms/Headline.vue
=> feat(storybook): added frontend env stuff

.storybook/webpack.config.js
=> fix(storybook): fix postcss plugins

.travis.yml
=> fix(travis): fix deploy, added edge for travis deployment v2

src/components/atoms/Headline.vue, src/layouts/default.vue, src/utils/fonts.js
=> fix(font-loader): add font-style

.travis.yml
=> fix(travis-preview): add keep_history property

renovate.json
ignore husky & lint-staged for using the sourcetree under osx
=> chore(renovate): add ignored deps husky & lint-staged

config.code-workspace, package-lock.json, package.json, src/components/layouts/TwoColumnContainer.vue, src/components/molecules/LinkList.vue
- disable builtin formatting for use with eslint and stylelint.
- clean recommendations extensions
- remove postcss-language, use stylelint as postcss linter and formatter
- update vscode config, disable builtin formatter
- remove eslint-plugin-vue from eslint config and package, is integrated in nuxtjs extend
- LinkList adapted for use without i18n
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to …
=> feat(update-clean): clean package, config and update components

.travis.yml
=> fix(mocha): updated package version

renovate.json
=> fix(renovate): automerge packages (excluded major updates)

config.code-workspace
=> feat(vscode-config): added npm intellisense plugin

package-lock.json, package.json
=> fix(storybook): added removed babel-preset-vue plugin

src/app/router.scrollBehavior.js, src/components/atoms/ResponsiveVideo.vue
- replaced scrollBehavior with newest version
- fix empty resource in responsive-image
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …
=> fix(update): update scrollBehavior and fix empty resource

nuxt.config.js
=> fix(robots): add basePath

package-lock.json
=> fix(audit): solved vulnerabilities

renovate.json
=> fix(renovate): automerge

.travis.yml, nuxt.config.js
=> chore(package-json): clean host port definitions

package-lock.json, package.json
=> fix(packages): updated versions

package-lock.json, package.json
=> fix(package): updated versions
